### PR TITLE
Handle {MATCHTITLE} in get5_hostname_format

### PR DESCRIPTION
**Pull request by Drarig29**
Here's the only need change needed for this feature request : #510.

If you are OK with it, [this page](https://github.com/splewis/get5/wiki/Full-list-of-get5-cvars) of the Wiki will need to be updated.

### CODE REVIEW

**Comment by topjor** [comment]
I would implement this in the format cvar string function, this way it is available to all strings that get formated with cvars like demo name etc.
https://github.com/splewis/get5/blob/2cb92339e4cce679b890d250d69c219aa03389f7/scripting/get5.sp#L1390

**Comment by Drarig29** [comment]
Actually, yes good idea. I couldn't find this function when searching `"{MATCHID}"` and other substitute format values on GitHub...

**Comment by topjor** [comment]
I always use my IDE to search in a project, I trust that way more and also makes looking at the code a lot easier

**Comment by Drarig29** [comment]
Lol, same for me. But I don't know... this time I first researched a way to do it on GitHub and then I made the change on my IDE in my fork. Anyway 😅

**Comment by splewis** [comment]
Thanks! I'll update the wiki.

**Pull request merged**
