### PR TITLE
Add hungarian translation

### PR DESCRIPTION
**Pull request by nickdnk**
Messed up the 0.9 merge, so this is a replacement PR for https://github.com/splewis/get5/pull/797

@enerbewow: Download test version with Hungarian translation here: https://github.com/splewis/get5/actions/runs/2767755954

### CODE REVIEW

**Comment by enerbewow** [comment]
I tested it and works smooth. One little thing.

When I did something unusual (mp_maxround 6 when I was in the 4th round) and when I won the final round, the end game announcement isn't worked. TeamWonMatchInfoMessage
[Get5] Won the match without the team name

**Comment by enerbewow** [comment]
In my case:
[Get5] megnyerte a mérkőzést.

**Comment by enerbewow** [comment]
I did a match with current players on server

**Comment by nickdnk** [comment]
Alright. That's a separate issue though, as your translation file is correct. We will have to file an issue for that specifically.

**Pull request merged**
