### PR TITLE
Hungarian transcription

### PR DESCRIPTION
**Pull request by enerbewow**

### CODE REVIEW

**Comment by enerbewow** [comment]
Sorry I am very bad with git. The latest 3695f6b push is contain a Hungarian transcription.
I wasn't seen much translator in Hungary so if any of my country users want to use get5 in Hungarian language, there you go.

**Comment by nickdnk** [comment]
Hello @enerbewow 

We're in the middle of a pretty big upgrade to Get5 (version 0.9), so I'm going to put this on hold until that has been released and then we can look into rebasing it on master and making sure it's all right.

Thanks for your contribution - much appreciated.

**Comment by nickdnk** [comment]
Hello @enerbewow 

We changed a few things. Can I get you to change these translations, according to the documentation under https://splewis.github.io/get5/translations/#reference - specifically the things changed here: https://github.com/splewis/get5/commit/aea2babeb4cc1553794ee14365553b5dbfb95801#diff-8b3d1143f9b736bdc7e82d4a26c5a581ea0968039d29edac1f29bde27dae3b3d

Note that team name parameters were added to:
`MaxPausesUsedInfoMessage`
`MaxPausesTimeUsedInfoMessage`

**Comment by nickdnk** [comment]
Also please remove all instances of `"#format" "{1:s},{2:d},{3:s}"` from your translated file. The format specifies should only be present in the English version.

**Comment by enerbewow** [comment]
I will go through on every line again and add/remove/fix lines

**Comment by nickdnk** [comment]
@enerbewow Alright. Just copy the translation file to a new file outside the repo, then run `git fetch --all`, reset your branch to "development", then copy the file back and commit and force-push.

**Comment by enerbewow** [comment]
We can close this

**Pull request closed without merging**
