### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by NUM1337**
1. Changed goinglive.sp to handle 10seconds restart or oldschool LO3 with old cvar get5_quick_restarts.
2. Changed colors at printing live score. Green for winning team, red for losing team, light blue for draw.
3. Gave free armor @ warmup

PS. My skills at programming are not good, but I think that it's ok. I have tested it out at my server with both version of get5_quick_restarts and it works fine but check it for safety.

### CODE REVIEW

**Comment by splewis** [comment]
There are a few issues with this.
1. Compile warnings: https://travis-ci.org/splewis/get5/jobs/138234094#L351
2. You've grouped at least 4 completely different things together 

I'm not sure that I'm a fan of the stylistic color changes. The other changes seem fine.

**Comment by NUM1337** [comment]
1. This warning are about bad code formatting, maybe i used somewhere space/tab instead of enter. I'll fix it later.
2. What do You mean by that?

By color changes You mean this green/red function yea? Hmm, ok i will keep this colors to myself :)

**Comment by splewis** [comment]
I meant it's usually bad practice to put together these 4 changes in a single pull request, since it makes it harder for me to take the parts that are actually wanted (i.e., everything but the coloring).

**Comment by NUM1337** [comment]
Ok, next time I will do it better. Thanks for the explanation!

**Pull request closed without merging**
