### PR TITLE
Allow for backup prefix

### PR DESCRIPTION
**Pull request by nickdnk**
Inspired by https://github.com/splewis/get5/pull/650, this should allow you to put backups into subfolders on your server. Not thoroughly tested yet.

Not meant to be included in 0.9. Just a proposal here.

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
I think #344 should be linked for this as well.

**Comment by nickdnk** [comment]
Yes, I did also add code to make the list function work with prefixes.

**Comment by nickdnk** [comment]
Fixes https://github.com/splewis/get5/issues/344.

**Comment by nickdnk** [comment]
This should be ready for some testing if you feel like it @PhlexPlexico.

**Comment by PhlexPlexico** [comment]
I'll get my machines up tomorrow here and test this as well! Sorry it's taken so long

**Comment by nickdnk** [comment]
So the current commit allows directories in the prefix, but only if they already exist. I'm working on some code that recursively creates directories, but I'm not quite done yet.

**Comment by nickdnk** [comment]
As of this comment, this seems to work pretty well.

It supports creating nested subfolders, including with the {MATCHID} variable, i.e. `backups/{MATCHID}/`, and both the `get5_loadbackup` and `get5_listbackups` functions work fine with this.

I've renamed it to `get5_backup_path`, as you **must** include a forward slash in the variable, so it cannot be used just as a file prefix. It must be a subfolder structure.

Please give it a go.

**Review by PhlexPlexico — APPROVED** [review]
Tested on backups and restores, and it seems to be working for me.

**Comment by nickdnk** [comment]
I just adjusted the code that handles automatic deletion of backups so it still works.

Also stressed in the docs the importance of a trailing slash in the backup path.

**Pull request merged**
