### PR TITLE
added docker container for building and build instructions

### PR DESCRIPTION
**Pull request by Apfelwurm**
for an easy build process when developing on get5 i've written a little dockerfile and the instructions how to use it.

### CODE REVIEW

**Comment by Apfelwurm** [comment]
Typing error in readme...

**Comment by Apfelwurm** [comment]
closed the wrong one... not my best day :D

**Comment by splewis** [comment]
Thanks!

**Comment by Drarig29** [comment]
@Apfelwurm It seems we need to build the image and run it each time a change is done in the code. Is it right?

Could there be a way of just running the same image after a change in the code?

**Comment by Apfelwurm** [comment]
@Drarig29 currently thats the case because of the submodule initialisation, the sourcemod download and the SteamWorks.inc download. 
Indeed it would be much better to do it like you mentioned. But therefore i would have to write a script which would be executed when launching the container which does the cleanup. I try to schedule the changes for the next week to clean this up :)

**Comment by Drarig29** [comment]
Nice! Thanks you 😃

**Comment by Apfelwurm** [comment]
@Drarig29 https://github.com/splewis/get5/pull/587 :)

**Pull request merged**
