### PR TITLE
Add pt(BR) translation

### PR DESCRIPTION
**Pull request by gabrielfgularte**
Now it's good (I think). Without `#format` lines.

Thank you!

### CODE REVIEW

**Comment by Technoblazed** [comment]
Why do you keep opening and closing pull requests?

**Comment by Technoblazed** [comment]
No one is bothered about the number of commits in a PR, sure it looks nicer, but as long as the job gets done, who cares.

**Comment by gabrielfgularte** [comment]
Sorry. I've tried twice to keep a fork of get5 making changes in master branch and use a custom branch to have my own modifications. But I've messed up all the two times. Also, I'm keeping duplicated file versions of get5 and I have edited, commited and pushed wrong files. =/

Let me stay more focused and keep things clearly on my local workflow, then I'll make good and concisely PR's. Sorry for those two closed PR's.

**Comment by Technoblazed** [comment]
Do you want me to do the PR for you quickly? Also did you manage to figure out the compiling?

**Comment by gabrielfgularte** [comment]
> Do you want me to do the PR for you quickly?

I can email you the translate file if you want. But I think that I can make a good PR tomorrow.

> Also did you manage to figure out the compiling?

Yes too! Thanks to you!

**Comment by Technoblazed** [comment]
Is it just the above files that are on this PR?

**Comment by gabrielfgularte** [comment]
For the translation is just one file: `get5.phrases.txt`.

The files above are including the `!switch` command on the `get.sp` file. That's why I've closed this PR. I've "misscommited" the `get.sp` file and I don't know how to remove it after push.

**Comment by Technoblazed** [comment]
Just push it again ;) I'm sending the PR's now

**Comment by gabrielfgularte** [comment]
Alright! Thank you!

**Pull request closed without merging**
