### PR TITLE
Create chat-based map selection system

### LINKED ISSUE #391: Add option for chat-based vetoing instead of menus
E.g. users type them out:

.ban de_dust2
.ban de_vertigo
.pick de_train

and such. Probably just choosable by cvar.

### PR DESCRIPTION
**Pull request by nickdnk**
Closes #391.

It works like:

```
!pick de_vertigo
!ban de_vertigo
```
`!ct` or `!t` to pick a side

During veto, all players except captain cannot type in all-chat, only team chat. This can be disabled with `get5_mute_allchat_during_map_selection 0`.

The system defaults to disabled but can be enabled with `get5_map_selection_via_chat 1` - thoughts?

Anything you would like to see changed?

### CODE REVIEW

**Review by EllyssonMike — APPROVED** [review]
That's right!

**Comment by nickdnk** [comment]
I'm considering removing the menus, or at least making them non-default. I have a hard time seeing any case where menus would be preferred.

**Comment by Apfelwurm** [comment]
German:
```
    "MapSelectionTeamChatOnly"
    {
        "de"        "Du kannst während die Kartenauswahl läuft nur im Teamchat schreiben."
    }
    "MapSelectionInvalidMap"
    {
        "de"        "{1} ist keine gültige Karte."
    }
    "MapSelectionPickMapHelp"
    {
        "de"        "Tippe {1} <Karte> um eine Karte auszuwählen ."
    }
    "MapSelectionBanMapHelp"
    {
        "de"        "Tippe {1} <Karte> um ein Veto gegen eine Karte einzulegen."
    }
    "MapSelectionPickSideHelp"
    {
        "de"        "Tippe {1} oder {2} um eine Seite auszuwählen."
    }
    "MapSelectionAnnounceCaptains"
    {
        "de"        "Captain für das Team {1}: {2}"
    }
    "MapSelectionBan"
    {
        "de"        "VETO"
    }
    "MapSelectionPick"
    {
        "de"        "AUSWÄHLEN"
    }
    "MapSelectionTurnToPick"
    {
        "de"        "{1} muss jetzt eine Karte {2} die als {3} Karte gespielt wird."
    }
    "MapSelectionTurnToBan"
    {
        "de"        "{1} muss jetzt ein {2} gegen eine Karte einlegen."
    }
    "MapSelectionPickSide"
    {
        "de"        "{1} muss jetzt eine Seite für die Karte {2} auswählen."
    }
    "MapSelectionRemainingMaps"
    {
        "de"        "Verbleibende Karten:"
    }

```

**Comment by RuneNyhuus** [comment]
How to get the old menu's back ?
If you dont like the new chat selection...
Too many make type errors and such

**Comment by nickdnk** [comment]
> How to get the old menu's back ?
> 
> If you dont like the new chat selection...
> 
> Too many make type errors and such

Use an older version. It's not coming back. I don't understand how users cannot spell the map names even when presented with the options and how to spell them. They don't even have to type the full name; `!ban mir` would ban Mirage.

It's just a matter of adapting to the change, and the old system had too many issues with people accidentally banning or picking the wrong map because of the key bindings overlapping with weapon selection.

**Comment by nickdnk** [comment]
> > > How to get the old menu's back ?
> 
> > > If you dont like the new chat selection...
> 
> > > Too many make type errors and such
> 
> > 
> 
> > Use an older version. It's not coming back. I don't understand how users cannot spell the map names even when presented with the options and how to spell them. They don't even have to type the full name; `!ban mir` would ban Mirage.
> 
> > 
> 
> > It's just a matter of adapting to the change, and the old system had too many issues with people accidentally banning or picking the wrong map because of the key bindings overlapping with weapon selection.
> 
> 
> 
> You have good point there.

I would suggest you give it a bit more time. Players will learn. You can also disable formatting of known map names if you would prefer them to be printed as their filename. See https://splewis.github.io/get5/latest/configuration/#get5_format_map_names.

**Pull request merged**
