### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by jpotier**

### CODE REVIEW

**Comment by Technoblazed** [comment]
You're missing all of the `#format` tags from the original code. This translation will not work, please fix your errors.

**Comment by jpotier** [comment]
Oh, I thought those were to be removed (that's what I was told for a translation of https://github.com/splewis/csgo-retakes)

**Comment by Technoblazed** [comment]
I'm mistaken, checked the translations page, should be fine :(

**Comment by jpotier** [comment]
Plus, not any of the other translations have the `"#format"` lines… Are you sure I should add them?

**Comment by splewis** [comment]
Thanks!

**Pull request merged**
